#!/usr/bin/env bash
#Setup Header on web-01 and web-02 server

#get updates
sudo apt-get update

#install nginx server
sudo apt-get -y install nginx

# configure firewall
sudo ufw allow 'Nginx HTTP'

# Grant user ownership to website folder for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#  create required page
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# configure redirect for "/redirect_me" and 404 error page
# add header tag X-Served-By to display hostname
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me http://johnchioma.tech permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
# Restart nginx server
sudo service nginx restart
