#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
#	Configure HAproxy so that it send traffic to web-01 and web-02
#	Distribute requests using a roundrobin algorithm
#	Make sure that HAproxy can be managed via an init script
#	Configure servers with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.

# Update sys
sudo apt-get -y update

# Install HAproxy
sudo apt-get -y install haproxy

# Server config
server_config=\
"
frontend http
        bind 0:80
	mode http
        default_backend web_servers

backend web_servers
        balance roundrobin
	server 117617-web-01 35.174.200.91:80
        server 117617-web-02 35.153.79.121:80
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

#Restart HAproxy Server
sudo service haproxy restart
